title: "Otaku Treasures"
description: "A site about anime and manga"
baseurl: "https://sujala99.github.io/Otaku-Treasures/"  # Set your baseurl
url: "https://github.com/Sujala99/Otaku-Treasures"  # Your GitHub Pages URL